#!/bin/bash

set -eu

echo "Installing go..."

bins=(
"go"
"gofmt"
)

prefix=$(dirname "$DOCKER_APP_PATH")/go
resolved=$(readlink "$DOCKER_APP_BASE/bin/go")

if [[ $resolved == $prefix* ]]; then
	for bin in "${bins[@]}"; do
		rm "$DOCKER_APP_BASE/bin/$bin"
		ln -s "$DOCKER_APP_PATH/$bin" "$DOCKER_APP_BASE/bin/"
	done
fi
